home/urls.py
from django.urls import path, re_path
from django.conf.urls import url

from .views import index
from .views import detail
from .views import contact
from .views import tag
from .views import search
# from .views import test404
# from .views import test500


app_name = 'home'
urlpatterns = [
    # hostname/home
    path('',index ,name='index'),
    
    url(r'^results/(?P<name>.+)/$', search, name='search'),

    # hostname.ex/detail/ 
    path('post/<slug:slug>/', detail , name = 'detail'),
    # hostname.ex/tag/linux/ 
    path('tag/<slug:slug>/', tag , name = 'tag'),
    # hostname.ex/contact
    path('us/contact', contact, name='contact'),

    # Error Handeling
    # path('404/', test404),
    # path('500/', test500),
]


myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


handler404 = 'home.views.handler404'
handler500 = 'home.views.handler500'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField
import os
from django.utils.html import format_html

class Tag(models.Model):
    name = models.CharField(max_length = 200)
    slug = models.SlugField(max_length=100)
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    pic = models.ImageField(upload_to="cover/")
    body = RichTextField()
    published = models.DateTimeField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tag = models.ManyToManyField(Tag)

    STATUS_CHOICES = (
        ('deaft', 'Draft'),
        ('published' , 'Published')
    )
    status = models.CharField(max_length=60 , choices=STATUS_CHOICES , default= 'draft')

    REC_CHOICES = (
        ('yes', 'Yes'),
        ('no', 'No'),
    )
    recommend = models.CharField(max_length=60 , choices=REC_CHOICES , default= 'no')

    def __str__(self):
        return self.title
    
    def thumbnail(self):
        return format_html("<img src='{}' width='80' height='50' style='border-radius: 5px;'>".format(self.pic.url))



home/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.shortcuts import (
    HttpResponse, get_list_or_404, get_object_or_404, render)


from .models import Post, Tag

# Create your views here.

def tags():
    return Tag.objects.all()

def paginator(request, data, num):
    
    paginator = Paginator(data, num)
    page = request.GET.get('page')
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)
    index = items.number - 1
    max_index = len(paginator.page_range)
    start_index = index - 5 if index >= 5 else 0
    end_index = index + 5 if index <= max_index - 5 else max_index
    page_range = paginator.page_range[start_index:end_index]

    return items, page_range

def recommend():
    return Post.objects.filter(recommend="yes").order_by('-published')[:5]

def index(request):
    posts = Post.objects.filter(status='published').order_by('-published')

    pages = paginator(request, posts, 3)
    context = {
        'items' : pages[0],
        'tags' : tags,
        'recommend' : recommend,
    }
    return render(request, 'home/index.html', context)


def detail(request, slug):
    post = get_object_or_404(Post, slug = slug)

    context = {
        'post' : post,
        'tags' : tags,
        'recommend' : recommend,
    }
    return render(request, 'home/detail.html',context)

def contact(request):
    context = {
        'tags' : tags,
        'recommend' : recommend,
    }
    return render(request, 'home/contact.html', context)

def tag(request, slug):
    posts = Post.objects.filter(tag__slug = slug, status='published')
    pages = paginator(request, posts, 5)

    tag = Tag.objects.filter(slug=slug)

    context = {
        'items' :pages[0],
        'tag' : tag,
        'tags' : tags,
        'recommend' : recommend,
    }
    return render(request, 'home/taglist.html', context)

def search(request,name):

    query = request.GET.get('q')
    posts = Post.objects.filter(Q (status="published") , Q(title__icontains=query) | Q(body__icontains = query) ).order_by("-published")
    context = {
        'items' : posts,
        'tags' : tags,
        'query' : query,
        'recommend' : recommend,
    }

    return render(request, 'home/search.html', context)












# Error Handeling
def handler404(request, exception):
    return render(request , "error/404.html", status = 404)

# def test404(request):
#     return render(request , "error/404.html")

def handler500(request):
    return render(request , "error/500.html", status = 500)

# def test500(request):
#     return render(request , "error/500.html")

templates/home/comment.html
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
this.page.url = "https://omixoid.net/post/{{url}}/" ;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = "{{url}}"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://omixoid.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            

templates/home/contact.html
{% extends 'partials/main.html' %}
{% block title %}Contact{% endblock title %}

{% block body %}
  <!-- Page Content -->
  <div class="container">
    <div class="row mt-3">
      <!-- Blog Entries Column -->
      <div class="col-md-8">
        <h4>تماس و درباره</h4>
        <!-- Blog Post -->
        <div class="card shadow bg-white  border-primary border-top-0 border-right-0 border-left-0 border-width border-redi">
          
          <div class="col-md-12">
            <img class="card-img mt-4" src="/media/static/bio.svg" alt="Card image cap " width="500px" height="400px">
          </div>
            <div class="card-body">
                <p class="card-text">

                  <div class="text-muted">
                    وبلاگ نوشته شده با جنگو، 
                    فونت وزیر، فرانت بوت استرپ ۴، 
                    ایکن unicons، و ...
                  </div>
            </div>
        </div>
      </div>
      <!-- Sidebar Widgets Column -->
      {% include  'partials/sidebar.html' %}

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
{% endblock %}

templates/home/detail.html
{% extends 'partials/main.html' %}
{% block title %}{{post.slug}}{% endblock title %}
{% block body %}
{% load jformat %}
{% load widget_tweaks %}
{% load social_share %}
  <!-- Page Content -->
  <div class="container">
    <div class="row mt-3">
      <!-- Post -->
      <div class="col-md-8">
        <br>
        <div class="card mb-3 mt-3 shadow bg-white border-primary border-top-0 border-right-0 border-left-0 border-width border-radi">
          <div>
            <img class="card-img-top my-2 rounded-lg border-radi border-width" src="{{ post.pic.url}}" alt="Card image cap" width="600" height="400">
          </div>
          <div class="card-title mx-4 my-0">
            <h2 class="card-title">{{ post.title }}</h2>
            <small class="text-muted " style="font-size: medium;"><i class="uil uil-clock"></i>{{ post.published| jformat:"%A %d %b %y"  }}</small> 
          </div>
          <div class="card-body ">
            <p class="card-text">{{ post.body | safe }}</p>
            <small class="text-muted " style="font-size: medium;"><i class="uil uil-refresh"></i>{{ post.updated | jformat:"%A %d %b %y"  }}</small> 
          </div>
        </div>
          <div class="row">
            <div class="col-md-6 my-3 ">
              <h6>اشتراک گذاری <i class="uil uil-share"></i></h6>
                  {% post_to_facebook object_or_url%}
                  {% post_to_whatsapp  object_or_url%}
                  {% post_to_twitter  object_or_url%}
                  {% post_to_telegram "{{ post.title }}" object_or_url%}
            </div>

            <div class="col-md-6 my-3">
                <h6>تگ ها <i class="uil uil-tag-alt"></i></h6> 
                  {% for tag in post.tag.all  %}
                    <a href="{% url 'home:tag' tag.slug %}" class="badge badge-primary py-2 px-2 text-white shadow">
                      <span class="font-weight-normal">{{tag}}</span>
                    </a>
                  {% endfor %}
            </div>
          </div>
      </div>
      <!-- Sidebar -->
      {% include  'partials/sidebar.html' %}
    </div>
    

    <div class="row">
      <div class="col-md-8 ">
        <div class="card shadow bg-white border-primary border-bottom-0 border-right-0 border-left-0 border-width border-radi ">
          
          <div class="px-4 py-4">
            <h6>اگه نظری داری می تونی اینجا بنویسی  <i class="uil uil-comment-alt"></i></h6>
            {% include 'home/comment.html' with url=post.slug %}

          </div>
        </div>

      </div>
    </div>
  </div>
{% endblock %}

templates/home/index.html
{% extends 'partials/main.html' %}
{% block title %}Home{% endblock title %}
{% load jformat %}

{% block body %}
<div class="container">
  <div class="row mt-3">

    <div class="col-md-8">
      <h4>آخرین مطالب</h4>
      {% for post in items %}
        <div class="card mb-3 shadow bg-white border-primary border-top-0 border-right-0 border-left-0 border-width border-radi">
          <div class="row">
            <div class="col-md-5">
              <img class="card-img bd-placeholder-img border-radi px-2 py-2" width="100%" height="225" src="{{post.pic.url}}" alt="photo" >
            </div>

              <div class="card-img-overlay" >
              <a href="{% url 'home:tag' post.tag.first.slug %}" >
              <span class="badge badge-secondary font-weight-normal btn-outline-primary">{{ post.tag.first }}</span> 
              </a>
              </div>

            <div class="col-md-7 px-2">
              <div class="card-body ">
                <h5 class="card-title"> {{ post.title }} | <small class="text-muted "> <i class="uil uil-clock"></i> {{ post.published | jformat:"%d %b %y" }}</small></h5>
                <p class="card-text">{{ post.body |truncatechars:150 | safe  }}</p>
                <a href="{% url 'home:detail' post.slug %}" class="badge badge-primary py-2 px-2">ادامه <i class="uil uil-arrow-left"></i></a>

              </div>
            </div>
          </div>
        </div>
      {% endfor %}
      <!-- Pagination -->
      {% include  'partials/pagination.html' %}
    </div>
    <br>
    <!-- Sidebar Widgets Column -->
    {% include  'partials/sidebar.html' %}
    
  </div>
</div>
{% endblock %}


templates/home/search.html
{% extends 'partials/main.html' %}
{% load jformat %}
{% block title %}Search{% endblock title %}

{% block body %}
  <!-- Page Content -->
  
<div class="container">
  <div class="row mt-3">
      {{ results }}
    <div class="col-md-8">
      {% if items %}
          <h4> نتایج سرچ برای 
            <small>{{ query }}</small> :
          </h4>
          {% for post in items %}
            <div class="card mb-3 shadow bg-white border-primary border-top-0 border-right-0 border-left-0 border-width border-radi">
              
                <div class="row">
                  <div class="col-md-5">
                      <img class="card-img bd-placeholder-img border-radi px-2 py-2" width="100%" height="225" src="{{post.pic.url}}" alt="photo" >
                  </div>

                  <div class="card-img-overlay" >
                    <a href="{% url 'home:tag' post.tag.first.slug %}" >
                    <span class="badge badge-secondary font-weight-normal btn-outline-primary">{{ post.tag.first }}</span> 
                    </a>
                  </div>

                  <div class="col-md-7 px-2">
                      <div class="card-body ">
                      <h5 class="card-title"> {{ post.title }} | <small class="text-muted "> <i class="uil uil-clock"></i> {{ post.published | jformat:"%d %b %y" }}</small></h5>
                      <p class="card-text">{{ post.body |truncatechars:150 | safe  }}</p>
                      <a href="{% url 'home:detail' post.slug %}" class="badge badge-primary py-2 px-2">ادامه <i class="uil uil-arrow-left"></i></a>
                      </div>
                  </div>

                </div>
            </div>
          {% endfor %}
      {% else %}
        <div class="mt-4 text-center">
          <h4 class="text-center">هیچی پیدا نشد متاسفانه :)</h4>
          <img src="/media/static/search_not_found.svg" class="py-4" width="100%" height="500px" alt="photo">
        </div>
      {% endif %}
      <!-- Pagination -->
      {% include  'partials/pagination.html' %}
    </div>
    <br>
    <!-- Sidebar Widgets Column -->
    {% include  'partials/sidebar.html' %}
  </div>
</div>
{% endblock %}


templates/home/taglist.html
{% extends 'partials/main.html' %}
{% load jformat %}
{% block title %}Tags{% endblock title %}

{% block body %}

<div class="container">
  <div class="row mt-3">

    <div class="col-md-8">
      {% if items %}
       <h4> پست های مربوط به تگ {{ tag | first }}</h4>
        {% for post in items %}
          <div class="card mb-3 shadow bg-white border-primary border-top-0 border-right-0 border-left-0 border-width border-radi">
            <div class="row">
              <div class="col-md-5">
                <img class="card-img bd-placeholder-img border-radi px-2 py-2" width="100%" height="225" src="{{post.pic.url}}" alt="photo" >
              </div>

              {% for i in tag %}
                <div class="card-img-overlay" >
                <a href="{% url 'home:tag' i.slug %}" >
                <span class="badge badge-secondary font-weight-normal btn-outline-primary">{{i.name}}</span>
                </a>
                </div>
              {% endfor %}

              <div class="col-md-7 px-2">
                <div class="card-body ">
                  <h5 class="card-title"> {{ post.title }} | <small class="text-muted "> <i class="uil uil-clock"></i> {{ post.published | jformat:"%d %b %y" }}</small></h5>
                  <p class="card-text">{{ post.body |truncatechars:150 | safe  }}</p>
                  <a href="{% url 'home:detail' post.slug %}" class="badge badge-primary py-2 px-2">ادامه <i class="uil uil-arrow-left"></i></a><br>

                </div>
              </div>
            </div>
          </div>
        {% endfor %}
        {% else %}
          <div class="mt-4 text-center">
              <h4 class="mt-4">
                  پستی برای تگ
                  {{ tag | first }}
                  پیدا نشد :(
              </h4>
              <img src="/media/static/tag_not_found.svg" class="py-4" width="100%" height="400" alt="photo">
          </div>
        {% endif %}
      <!-- Pagination -->
      {% include  'partials/pagination.html' %}
    </div>
    <br>
    {% include  'partials/sidebar.html' %}
  </div>
</div>
{% endblock %}


templates/partials/footer.html
<footer class="container py-4 ">
    <div class=" text-center">
      به امید ساخت فردای بهتر  <i class="uil uil-nerd"></i>
    </div>
  </footer>

templates/partials/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="/media/static/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/media/static/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/media/static/favicon/favicon-16x16.png">
    <link rel="manifest" href="/media/static/favicon/site.webmanifest">
    <!-- Title -->
    <title>{% block title %}{% endblock title %} | Xo</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Icon -->
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v2.1.9/css/unicons.css">
    <!-- Static CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
</head>

<body >
    <!-- Partials Header -->
    {% include "./header.html" %}

    <!-- Partials Navigation -->
    <div class="container-fluid bg-light ">
        <!-- Navigation -->
        {% include "./navigation.html" %}

        <!-- Body -->
        {% block body %}
        {% endblock %}
        
        <!-- Partials Footer -->
        {% include './footer.html' %}
    </div>

    <!-- Dark Mode JS -->
    <script src="{% static 'js/dark-mode-switch.js' %}"></script>

    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Static JS -->
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

templates/partials/navigation.html
{% load static %}
<div class="container">
  <nav class="navbar navbar-expand-lg icon-bar sticky-top navbar-light bg-white shadow rounded-lg border-radi" >
    
    <a class="navbar-brand text-white " href="{% url 'home:index' %}">
      <img src="/media/static/logo.svg" height="35" width="70" alt="LOGO">
    </a>
    
    <div class="custom-control custom-switch">
      <input type="checkbox" class="custom-control-input" id="darkSwitch" />
      <label class="custom-control-label" for="darkSwitch"></label>
      
      <span class=>حالت شب<i class="uil uil-moon"></i></span>
    </div>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon text-dark"></span>
    </button>

    <div class="collapse navbar-collapse " id="navbarColor01">
      <ul class="navbar-nav mr-auto ml-4 ">
        <li class="nav-item active">
          <a class="nav-link text-dark" href="{% url 'home:index' %}">صفحه اول <i class="uil uil-home-alt"></i><span class="sr-only">(current)</span></a>
        </li>
        <!-- <li class="nav-item active">
          <a class="nav-link text-dark " href="{% url 'home:tag' "videocast" %}">ویدیو کست</a>
        </li> -->
        <li class="nav-item ">
          <a class="nav-link active text-dark get-started-btn scrollto" href="{% url 'home:contact' %}">تماس و درباره <i class="uil uil-user-square"></i></a>
        </li> 
      </ul>
      
      <form class="form-inline my-2 my-lg-0 " accept-charset="utf-8" method="GET" action="{% url 'home:search' "null" %}">
        <input class="form-control mr-sm-2 bg-light" type="text" placeholder="سرچ" name="q" value="{{ request.GET.q }}">
        <button class="btn btn-secondary my-2 my-sm-0 bg-primary " type="submit">
          <i class="uil uil-search"></i></button>
      </form>
      
    </div>
    
  </nav>
</div>

templates/partials/pagination.html

    <nav aria-label="Page navigation example ">
        {% if items.has_other_pages %}
            <ul class="pagination justify-content-center">
                {% if items.has_previous%}
                    <li class="page-item bg-white ">
                        <a class="page-link bg-white" href="{{ request.path }}?page={{ items.previous_page_number}}"><i class="uil uil-arrow-circle-right"></i></i></a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link bg-white" href="#"><i class="uil uil-arrow-circle-right"></i></a>
                    </li>
                {% endif %}

                {% for i in items.paginator.page_range %}
                    {% if items.number == i %}
                        <li class="page-item disabled">
                            <a class="page-link bg-white" href="#">{{ i }}</a>
                        </li>
                    {% else %}
                        <li class="page-item ">
                            <a class="page-link bg-white" href="{{ request.path }}?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if items.has_next %}
                    <li class="page-item">
                        <a class="page-link bg-white" href="{{ request.path }}?page={{ items.next_page_number}}"><i class="uil uil-arrow-circle-left"></i></a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link bg-white" href="#"><i class="uil uil-arrow-circle-left"></i></a>
                    </li>
                {% endif %}
            </ul>
        {% endif %}

    </nav>

templates/partials/sidebar.html
{% load jformat %}

<div class="col-md-4 mt-3">
    <!-- Search Widget -->
    <div class="card my-4 shadow bg-white border-primary border-top-0 border-right-0 border-bottom-0 border-width border-radi">
      <div class="card-body ">
        <h5><span class="border-bottom border-line ">اینجا ها هم هستم <i class="uil uil-share-alt"></i></span></h5><br>
        <div class="row">
          <div class="col-lg-12 list-group pl-3">
            <ul class="list-unstyled mb-0 text-center ">
              <li><a href="#" class=" border-0 shadow-sm rounded-pill mb-1 btn btn-outline-danger btn-block mb-2 py-2">
                یوتیوب(بزودی)
                <i class="uil uil-youtube"></i>
                </a>
              </li>
              <li><a target="_blank" href="https://www.instagram.com/omixoid/" class=" border-0 shadow-sm rounded-pill mb-1 btn btn-outline-secondary btn-block mb-2 py-2">اینستاگرام
                <i class="uil uil-instagram"></i>
              </a></li>
              <li><a target="_blank" href="https://t.me/omixoid/" class=" border-0 shadow-sm rounded-pill mb-1 btn btn-outline-primary btn-block mb-2 py-2">تلگرام
                <i class="uil uil-telegram-alt"></i>
              </a></li>
            </ul>
          </div>

        </div>
      </div>
    </div>
    <!-- Rigester Email
    <div class="form-group ">
      <label for="exampleInputEmail1">برای دریافت مطالب ایمیلتو وارد کن !</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="ایمیل">
      <small id="emailHelp" class="form-text text-muted"></small>
      <button type="submit" class="btn btn-primary">ثبت</button>
    </div> -->


    <!-- Tag Widget -->
    <div class="card my-4 shadow bg-white border-primary border-top-0 border-right-0 border-bottom-0 border-width border-radi">
      <div class="card-body">
        <h5><span class="border-bottom border-line ">تگ ها<i class="uil uil-tag-alt"></i></span></h5><br>
        <div class="row">
          <div class="col-lg-12">
            {% for tag in tags %}
            <a href="{% url 'home:tag' tag.slug %}" class="badge badge-primary py-1 text-white">
              <span class="font-weight-normal">{{tag.name}}</span>
            </a>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
    
    <div class="card my-4 bg-white shadow border-primary border-top-0 border-right-0 border-bottom-0 border-width border-radi">
     
      <div class="card-body ">
        <h5><span class="border-bottom border-line ">مطالب پیشنهادی <i class="uil uil-thumbs-up"></i></span></h5><br>
        {% for post in recommend %} 
          <ol class="list-unstyled ">
              <li><a href="{% url 'home:detail' post.slug %}" class="non-underline-link text-primary">{{ post.title }} </a></li>
          </ol>
        {% endfor %}
      </div>
    </div>
</div>